Setup es6 babel flow
verdaccio/verdaccio-auth-memory pull request #7
Opened 2018-07-24 20:57 UTC by ayusharma

Setup the following in repo
- Jest
- Flow
- Babel
- Eslint with prettier
- CircleCI
- Codecov

2018-07-25 04:43 UTC, juanpicado commented on .circleci/config.yml
> +version: 2
I'd use this version instead https://github.com/verdaccio/verdaccio-google-cloud/blob/master/.circleci/config.yml#L123 to publish from circleCI

2018-07-25 04:45 UTC, juanpicado commented on package.json
> +    "@verdaccio/types": "^3.4.1",
It's better without `^`

2018-07-25 04:46 UTC, juanpicado commented on package.json
> +    "flow-runtime": "0.17.0",
I think `flow-runtime` is not need it at all. The same applies to other projects. Can we do the test here?

2018-07-25 05:07 UTC, juanpicado commented on src/index.js
> +    verdaccioConfig: { max_users: number }
Here you can create your own Flow object extending `Config`, check this https://github.com/verdaccio/verdaccio-google-cloud/blob/master/src/data-storage.js#L24

2018-07-25 05:08 UTC, juanpicado commented on src/index.js
> +  authenticate(user: string, password: string, done: Function): Function {
`Function` should be `Callback`

2018-07-25 05:09 UTC, juanpicado commented on src/index.js
> +export default class Memory {
implements https://github.com/verdaccio/flow-types/blob/master/src/types.js#L372

2018-07-25 05:09 UTC, juanpicado commented on src/index.js
> +  adduser(user: Object, password: string, done: Function): Function {
user should be `RemoteUser`, check types

2018-07-25 05:09 UTC, juanpicado requested changes
🍰

2018-07-25 20:03 UTC, juanpicado commented on src/index.js
> +      const error = Error('not allowed to access package');
For errors we should not use native `Error`, instead in verdaccio we use https://github.com/verdaccio/local-storage/blob/master/src/local-fs.js#L8 

For now we can let it like that, but, in some point we have to centralize this https://github.com/verdaccio/verdaccio/blob/master/src/lib/utils.js#L354 in a package

2018-07-25 20:07 UTC, juanpicado requested changes
Almos there ..

2018-07-26 11:05 UTC, juanpicado commented on src/index.js
> +  adduser(user: Object, password: string, done: Callback): Callback {
`user: Object` .... `RemoteUser`

2018-07-26 11:10 UTC, juanpicado commented on package.json
> +    "in-publish": "^2.0.0",
Remove all `^`

2018-07-26 11:11 UTC, juanpicado commented on .npmignore
> +jestEnvironment.js
You shouls exclude `src` here I guess.

2018-07-26 11:12 UTC, juanpicado requested changes
Sorry, minor changes.

2018-07-26 12:25 UTC, ayusharma commented on .npmignore
> +jestEnvironment.js
`src` is not present here.

2018-07-26 12:37 UTC, juanpicado approved these changes
👍

2018-07-26 15:26 UTC, merged